Repository prom3theu5/aspirational-manifests, pull requests merged in 2025-02, with the labels that each got.

#284 fix: version check error if not connection
  src/Aspirate.Services/Implementations/VersionCheckService.cs
Labels: Review effort [1-5]: 1

#283 Net9 upgrade
  .github/workflows/main.yaml
  .github/workflows/pull-requests.yaml
  Directory.Packages.props
  src/Aspirate.Cli/Aspirate.Cli.csproj
  src/Aspirate.Commands/Aspirate.Commands.csproj
  src/Aspirate.Processors/Aspirate.Processors.csproj
  src/Aspirate.Processors/Transformation/Json/JsonExpressionProcessor.cs
  src/Aspirate.Secrets/Aspirate.Secrets.csproj
  src/Aspirate.Services/Aspirate.Services.csproj
  src/Aspirate.Services/Implementations/ContainerCompositionService.cs
  src/Aspirate.Services/Implementations/KubeCtlService.cs
  src/Aspirate.Shared/Aspirate.Shared.csproj
  src/Aspirate.Shared/Extensions/ComposeExtensions.cs
  src/Aspirate.Shared/Interfaces/Services/IShellExecutionService.cs
  src/Aspirate.Shared/Literals/AspireLiterals.cs
  tests/Aspirate.Tests/ActionsTests/ActionExecutorTests.cs
  tests/Aspirate.Tests/ActionsTests/BaseActionTests.cs
  tests/Aspirate.Tests/ActionsTests/Configuration/InitializeConfigurationActionTests.cs
  tests/Aspirate.Tests/ActionsTests/Configuration/LoadConfigurationActionTests.cs
  tests/Aspirate.Tests/ActionsTests/Containers/PopulateContainerDetailsForProjectsActionTests.cs
  tests/Aspirate.Tests/ActionsTests/Manifests/ApplyManifestsToClusterActionTests.cs
  tests/Aspirate.Tests/ActionsTests/Manifests/GenerateAspireManifestActionTests.cs
  tests/Aspirate.Tests/ActionsTests/Manifests/GenerateDockerComposeManifestActionTests.cs
  tests/Aspirate.Tests/ActionsTests/Manifests/GenerateKustomizeManifestsActionTests.cs
  tests/Aspirate.Tests/ActionsTests/Manifests/LoadAspireManifestActionTests.cs
  tests/Aspirate.Tests/ActionsTests/Manifests/RemoveManifestsToClusterActionTests.cs
  tests/Aspirate.Tests/ActionsTests/Secrets/PopulateInputsActionTests.cs
  tests/Aspirate.Tests/ActionsTests/Secrets/SaveSecretsActionTests.cs
  tests/Aspirate.Tests/Aspirate.Tests.csproj
  tests/Aspirate.Tests/DockerComposeTests/DockerComposeBuilderTests.cs
  tests/Aspirate.Tests/ExtensionTests/KubernetesDeploymentDataExtensionTests.cs
  tests/Aspirate.Tests/ProcessorTests/ContainerProcessorTests.cs
  tests/Aspirate.Tests/SecretTests/SecretProviderTests.cs
  tests/Aspirate.Tests/ServiceTests/AspirateConfigurationServiceTest.cs
  tests/Aspirate.Tests/ServiceTests/BaseServiceTests.cs
  tests/Aspirate.Tests/ServiceTests/ContainerCompositionServiceTest.cs
  tests/Aspirate.Tests/ServiceTests/ContainerDetailsServiceTests.cs
  tests/Aspirate.Tests/ServiceTests/ContainerOptionsTests.cs
  tests/Aspirate.Tests/ServiceTests/KubeCtlServiceTests.cs
  tests/Aspirate.Tests/ServiceTests/ManifestFileParserServiceTests.cs
  tests/Aspirate.Tests/ServiceTests/ProjectPropertyServiceTests.cs
  tests/Aspirate.Tests/ServiceTests/SecretServiceTests.cs
  tests/Aspirate.Tests/TestData/TestApp.csproj
Labels: Review effort [1-5]: 2

#263 Update README.md
  README.md
Labels: Review effort [1-5]: 1

#276 fix(#275): add support for the scheme property in endpoint bindings
  src/Aspirate.Processors/Transformation/Bindings/BindingProcessor.cs
  src/Aspirate.Processors/Transformation/Literals.cs
Labels: Review effort [1-5]: 1

#277 Possibility to specify manifest parameter values for generate command in non interactive mode (#274)
  src/Aspirate.Commands/Actions/Secrets/PopulateInputsAction.cs
  src/Aspirate.Commands/Commands/Generate/GenerateCommand.cs
  src/Aspirate.Commands/Commands/Generate/GenerateOptions.cs
  src/Aspirate.Commands/Options/ParameterResourceValueOption.cs
  src/Aspirate.Shared/Interfaces/Commands/Contracts/IGenerateOptions.cs
  src/Aspirate.Shared/Models/Aspirate/AspirateState.cs
Labels: Review effort [1-5]: 3

#273 Added options to build project resource container images using custom Dockerfile instead of 'dotnet publish'
  docs/Writerside/topics/Build-Command.md
  docs/Writerside/topics/Generate-Command.md
  docs/Writerside/topics/Init-Command.md
  docs/Writerside/topics/Run-Command.md
  src/Aspirate.Commands/Actions/Configuration/InitializeConfigurationAction.cs
  src/Aspirate.Commands/Actions/Containers/BuildAndPushContainersFromProjectsAction.cs
  src/Aspirate.Commands/Commands/Build/BuildCommand.cs
  src/Aspirate.Commands/Commands/Build/BuildOptions.cs
  src/Aspirate.Commands/Commands/Generate/GenerateCommand.cs
  src/Aspirate.Commands/Commands/Generate/GenerateOptions.cs
  src/Aspirate.Commands/Commands/Init/InitCommand.cs
  src/Aspirate.Commands/Commands/Init/InitOptions.cs
  src/Aspirate.Commands/Commands/Run/RunCommand.cs
  src/Aspirate.Commands/Commands/Run/RunOptions.cs
  src/Aspirate.Commands/Options/ContainerBuildArgsOption.cs
  src/Aspirate.Commands/Options/ContainerBuildContextOption.cs
  src/Aspirate.Commands/Options/PreferDockerfileOption.cs
  src/Aspirate.Processors/Resources/Project/ProjectProcessor.cs
  src/Aspirate.Services/Implementations/ContainerDetailsService.cs
  src/Aspirate.Shared/Inputs/ContainerOptions.cs
  src/Aspirate.Shared/Interfaces/Commands/Contracts/IBuildOptions.cs
  src/Aspirate.Shared/Interfaces/Commands/Contracts/IContainerOptions.cs
  src/Aspirate.Shared/Literals/ContainerBuilderLiterals.cs
  src/Aspirate.Shared/Literals/MsBuildPropertiesLiterals.cs
  src/Aspirate.Shared/Models/Aspirate/AspirateContainerSettings.cs
  src/Aspirate.Shared/Models/Aspirate/AspirateState.cs
  src/Aspirate.Shared/Models/MsBuild/MsBuildContainerProperties.cs
  tests/Aspirate.Tests/ServiceTests/ContainerDetailsServiceTests.cs
  tests/Aspirate.Tests/ServiceTests/ContainerOptionsTests.cs
  tests/Aspirate.Tests/ServiceTests/VerifyResults/ContainerDetailsServiceTests.GetContainerDetails_WhenCalled_ReturnsCorrectContainerDetails_properties=FullResponseWithDockerfileAndContext.verified.txt
Labels: Review effort [1-5]: 3

#287 ci: Add and configure Release Please
  .github/workflows/conventional-commits.yaml
  .github/workflows/release-please.yaml
  .release-please-manifest.json
  Aspirate.sln
  release-please-config.json
Labels: Review effort 2/5

#288 chore(main): release 9.0.0
  CHANGELOG.md
Labels: autorelease: pending, Review effort 1/5

#292 fix: nullability on build args in container building for projects. Cannot call ToDictionary on null.
  src/Aspirate.Commands/Actions/Containers/BuildAndPushContainersFromProjectsAction.cs
Labels: Review effort 1/5

#291 chore(main): release 9.0.1
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending, Review effort 1/5

#282 Manifest placeholder escape sequence support
  src/Aspirate.Processors/ServiceCollectionExtensions.cs
  src/Aspirate.Processors/Transformation/Bindings/BindingProcessor.cs
  src/Aspirate.Processors/Transformation/Bindings/IBindingProcessor.cs
  src/Aspirate.Processors/Transformation/Json/IJsonInterpolationUnescapeProcessor.cs
  src/Aspirate.Processors/Transformation/Json/JsonExpressionProcessor.cs
  src/Aspirate.Processors/Transformation/Json/JsonInterpolation.cs
  src/Aspirate.Processors/Transformation/Json/JsonInterpolationUnescapeProcessor.cs
  src/Aspirate.Processors/Transformation/ResourceExpressionProcessor.cs
  tests/Aspirate.Tests/ProcessorTests/ContainerProcessorTests.cs
  tests/Aspirate.Tests/ProcessorTests/JsonInterpolationTests.cs
Labels: Review effort [1-5]: 3

#294 chore(main): release 9.0.2
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending, Review effort 1/5

#298 Set 'clusterIP' to 'None' in the case of headless service.
  src/Aspirate.Shared/Extensions/KubernetesDeploymentDataExtensions.cs
Labels: Review effort 1/5

#297 Command Line Help Secret Masking
  src/Aspirate.Cli/AspirateCli.cs
  src/Aspirate.Cli/Program.cs
  src/Aspirate.Commands/Options/AllowClearNamespaceOption.cs
  src/Aspirate.Commands/Options/AspireManifestOption.cs
  src/Aspirate.Commands/Options/BaseOption.cs
  src/Aspirate.Commands/Options/ComposeBuildsOption.cs
  src/Aspirate.Commands/Options/ContainerBuildArgsOption.cs
  src/Aspirate.Commands/Options/ContainerBuildContextOption.cs
  src/Aspirate.Commands/Options/ContainerBuilderOption.cs
  src/Aspirate.Commands/Options/ContainerImageTagOption.cs
  src/Aspirate.Commands/Options/ContainerRegistryOption.cs
  src/Aspirate.Commands/Options/ContainerRepositoryPrefixOption.cs
  src/Aspirate.Commands/Options/DisableSecretsOption.cs
  src/Aspirate.Commands/Options/DisableStateOption.cs
  src/Aspirate.Commands/Options/IBaseOption.cs
  src/Aspirate.Commands/Options/ImagePullPolicyOption.cs
  src/Aspirate.Commands/Options/IncludeDashboardOption.cs
  src/Aspirate.Commands/Options/InputPathOption.cs
  src/Aspirate.Commands/Options/KubernetesContextOption.cs
  src/Aspirate.Commands/Options/LaunchProfileOption.cs
  src/Aspirate.Commands/Options/NamespaceOption.cs
  src/Aspirate.Commands/Options/NonInteractiveOption.cs
  src/Aspirate.Commands/Options/OutputFormatOption.cs
  src/Aspirate.Commands/Options/OutputPathOption.cs
  src/Aspirate.Commands/Options/ParameterResourceValueOption.cs
  src/Aspirate.Commands/Options/PreferDockerfileOption.cs
  src/Aspirate.Commands/Options/PrivateRegistryEmailOption.cs
  src/Aspirate.Commands/Options/PrivateRegistryOption.cs
  src/Aspirate.Commands/Options/PrivateRegistryPasswordOption.cs
  src/Aspirate.Commands/Options/PrivateRegistryUrlOption.cs
  src/Aspirate.Commands/Options/PrivateRegistryUsernameOption.cs
  src/Aspirate.Commands/Options/ProjectPathOption.cs
  src/Aspirate.Commands/Options/ReplaceSecretsOption.cs
  src/Aspirate.Commands/Options/RollingRestartOption.cs
  src/Aspirate.Commands/Options/RuntimeIdentifierOption.cs
  src/Aspirate.Commands/Options/SecretPasswordOption.cs
  src/Aspirate.Commands/Options/SkipBuildOption.cs
  src/Aspirate.Commands/Options/SkipFinalKustomizeGenerationOption.cs
  src/Aspirate.Commands/Options/TemplatePathOption.cs
  src/Aspirate.Secrets/MaskedValue.cs
  tests/Aspirate.Tests/SecretTests/MaskedValueTests.cs
Labels: Review effort 3/5

#304 chore(main): release 9.0.3
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#306 chore(main): release 9.0.4
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending
